apiVersion: v1
kind: Pod
metadata:
  name: ib-test-pod
spec:
  containers:
  - name: app
    image: centos/tools
    command: ["sleep", "infinity"]
    resources:
      limits:
        ten1010.io/if-infiniband-200g: 1